# Generated by Django 5.1.3 on 2024-12-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_user_is_staff"),
    ]

    operations = [
        migrations.RemoveField(model_name="budget", name="end_date",),
        migrations.RemoveField(model_name="budget", name="start_date",),
    ]
