# Generated by Django 5.1.3 on 2024-12-11 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_remove_budget_end_date_remove_budget_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="category",
            field=models.ForeignKey(
                limit_choices_to={"category_type": "Expense"},
                on_delete=django.db.models.deletion.CASCADE,
                to="base.category",
            ),
        ),
    ]
